# Generated by Django 3.2.3 on 2021-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('name', models.CharField(max_length=1000)),
                ('number', models.IntegerField()),
                ('distance', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'WelbeXTable',
                'ordering': ['data'],
            },
        ),
    ]
